#!/usr/bin/env bash
# Deploy the latest local dashboard (code + precomputed data) to Vercel.
#
# Usage:
#   ./deploy.sh                     # deploy current state to production
#   ./deploy.sh --precompute        # run precompute first, then deploy
#   ./deploy.sh --preview           # deploy as a preview, not production
#
# Why this script exists:
# - Vercel git integration is not connected for this project, so deploys
#   must be triggered from CLI.
# - The repo's .gitignore excludes /public/data/ and /public/papers/
#   (they are regenerated by the precompute pipeline). Vercel's CLI falls
#   back to .gitignore when no .vercelignore is present, which is why an
#   earlier production deploy went out with empty data and empty panels.
#   The committed .vercelignore in this directory overrides that fallback;
#   this script also sanity-checks the data directory before pushing so
#   we never repeat the empty-deploy mistake.

set -euo pipefail

cd "$(dirname "$0")"

PRECOMPUTE=0
PREVIEW=0
for arg in "$@"; do
  case "$arg" in
    --precompute) PRECOMPUTE=1 ;;
    --preview)    PREVIEW=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "Unknown flag: $arg"; exit 2 ;;
  esac
done

# 1. Optional precompute. Activates the project venv one level up.
if [[ "$PRECOMPUTE" -eq 1 ]]; then
  echo "==> Running precompute pipeline..."
  pushd .. >/dev/null
  source backend/venv/bin/activate
  python -m dashboard.scripts.precompute || python dashboard/scripts/precompute.py
  deactivate
  popd >/dev/null
fi

# 2. Sanity-check the data directory before uploading. An empty data dir
#    means the dashboard would deploy with empty panels; bail loud rather
#    than silently shipping a broken survey.
DATA_DIR="public/data"
if [[ ! -d "$DATA_DIR" ]]; then
  echo "ERROR: $DATA_DIR not found. Run with --precompute or generate data first."
  exit 1
fi
DATA_FILES=$(find "$DATA_DIR" -name '*.json' | wc -l | tr -d ' ')
DATA_BYTES=$(du -sk "$DATA_DIR" | awk '{print $1}')
if [[ "$DATA_FILES" -lt 5 || "$DATA_BYTES" -lt 200 ]]; then
  echo "ERROR: $DATA_DIR looks empty ($DATA_FILES json files, ${DATA_BYTES}KB)."
  echo "       Run with --precompute or regenerate the precomputed JSONs first."
  exit 1
fi
echo "==> Data check passed: $DATA_FILES JSON files, ${DATA_BYTES}KB."

# 3. Confirm .vercelignore exists. Without it Vercel falls back to
#    .gitignore which strips public/data — the empty-panel bug.
if [[ ! -f .vercelignore ]]; then
  echo "WARNING: .vercelignore is missing. Without it, Vercel uses .gitignore"
  echo "         and your data directory will be excluded from the deploy."
  echo "         Aborting to avoid an empty-panel deploy."
  exit 1
fi

# 4. Deploy.
if [[ "$PREVIEW" -eq 1 ]]; then
  echo "==> Deploying preview..."
  vercel deploy --yes
else
  echo "==> Deploying production..."
  vercel deploy --prod --yes
fi

echo "==> Done. Live at: https://grasp-explorer-dashboard.vercel.app/"
